### ISSUE TITLE
Taksit zorunlu hatası

### ISSUE THREAD

**Issue by mcakmakali** [optimisthub/moka-woocommerce#16]
Müşterilerin geri bildirimlerinden dönen bir hatayı paylaşmak istiyorum. Taksit kapalı olmasına rağmen Taksit seçmek zorunludur hatası ile karşılaşıyorlar sanırım bu hata farklı tarayıcılarla çakışan bir durum diye düşünüyorum.

**Comment by fatihtoprak** [comment]
Merhaba eklenti ve WordPress versiyonunuz güncel midir ?

Farklı eklentileri kapatıp sadece moka ve woocommerce eklentisi ile deneyimleyip tarayıcı konsolunuzda hata var ise paylaşabilir misiniz ?

**Comment by mcakmakali** [comment]
Şu an canlıda olan web sayfasında diğer eklentileri maalesef kapatamam. Ben test edince hatayı almıyorum ama 3 4 kişiden böyle geri dönüş geldi. Tekrar hatayı alırsak eğer ekran görüntüsü ve consol ekranını paylaşacağım.

**Comment by fatihtoprak** [comment]
teşekkürler sorun olması halinde bilgilendirmenizi rica ederim. bu issue kapatıyorum.
