### ISSUE TITLE
Etkinleştirme hatası

### ISSUE THREAD

**Issue by kadirturan0** [optimisthub/moka-woocommerce#17]
Merhaba eklentiyi etkinleştirince şöyle bir hata alıyorum.

"Eklenti etkinleştirilemedi, çünkü önlenemeyen bir hataya sebep oldu.

Fatal error: Cannot redeclare wp_install_maybe_enable_pretty_permalinks() (previously declared in /home/***/public_html/****/wp-admin/includes/upgrade.php:470) in /home/***/public_html/****/wp-admin/includes/upgrade.php on line 469

"

WooCommerce sürümümüz: : 7.1.0
WordPress sürümü: 6.1
PHP sürümü: 7.4.33

**Comment by fatihtoprak** [comment]
Merhaba kullandığınız diğer eklentileri kapatıp denediğinizde aynı sorunu yaşıyor musunuz ?

**Comment by solosapiens0** [comment]
Evet aynı hatayı aldım az önce, woocommerce hariç eklentileri devre dışı bırakıp etkinleştirdiğimde sorun olmadı.

**Comment by solosapiens0** [comment]
Bende Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue bu eklenti etkin iken moca yukarıdaki hatayı veriyor.

**Comment by solosapiens0** [comment]
2022/11/16 13:15:24 [error] 1656973#1656973: *31213 FastCGI sent in stderr: "PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/clients/client1/web41/web/wp-content/plugins/moka-woocommerce-master/core/library/Moka_Init.php on line 188PHP message: PHP Fatal error:  Uncaught TypeError: current(): Argument #1 ($array) must be of type array, bool given in /var/www/clients/client1/web41/web/wp-content/plugins/moka-woocommerce-master/core/library/Moka_Init.php:191
Stack trace:
#0 /var/www/clients/client1/web41/web/wp-content/plugins/moka-woocommerce-master/core/library/Moka_Init.php(191): current()
#1 /var/www/clients/client1/web41/web/wp-includes/class-wp-hook.php(310): Moka_Init->renderMinInstallmentMessage()
#2 /var/www/clients/client1/web41/web/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#3 /var/www/clients/client1/web41/web/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(1872): apply_filters()
#4 /var/www/clients/client1/web41/web/wp-content/plugins/woocommerce/templates/single-product/price.php(25): WC_Product->get_price_html()
#5 /var/www/clients/client1/web41/web/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('...')#6 /var/www/clients/client1/web41/web/wp-cont" while reading response header from upstream, client: 85.105.152.179, server: dev.xxx.com.com, request: "GET /polti-unico-mcv85-total-clean-turbo-6-bar-buharli-multisiklonik-vakumlu-elektrikli-supurge/ HTTP/2.0", upstream: "fastcgi://unix:/var/lib/php7.4-fpm/web41.sock:", host: "dev.xxx.com.com", referrer: "https://dev.xxx.com/"

**Comment by solosapiens0** [comment]
2022/11/16 13:32:10 [error] 1720456#1720456: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  current() expects parameter 1 to be array, bool given in /var/www/clients/client1/web41/web/wp-content/plugins/moka-woocommerce-master/core/library/Moka_Init.php on line 191PHP message: PHP Warning:  current() expects parameter 1 to be array, bool given in /var/www/clients/client1/web41/web/wp-content/plugins/moka-woocommerce-master/core/library/Moka_Init.php on line 191PHP message: PHP Warning:  current() expects parameter 1 to be array, bool given in /var/www/clients/client1/web41/web/wp-content/plugins/moka-woocommerce-master/core/library/Moka_Init.php on line 191PHP message: PHP Warning:  current() expects parameter 1 to be array, bool given in /var/www/clients/client1/web41/web/wp-content/plugins/moka-woocommerce-master/core/library/Moka_Init.php on line 191PHP message: PHP Warning:  current() expects parameter 1 to be array, bool given in /var/www/clients/client1/web41/web/wp-content/plugins/moka-woocommerce-master/core/library/Moka_Init.php on line 191PHP message: PHP Warning:  current() expects parameter 1 to be array, bool given in /var/www/clients/client1/web41/web/wp-content/plugins/moka-woocommerce-master/core/library/Moka_Init.php on line 191PHP message: PHP Warning:  current() expects parameter 1 to be array, bool given in /var/www/clients/client1/web41/web/wp-content/plugins/moka-woocommerce-master/core/library/Moka_Init.php on line 191" while reading response header from upstream, client: 8x.xxx.xxx.xxx, server: dev.xxx.com, request: "GET /xxx/ HTTP/2.0", upstream: "fastcgi://unix:/var/lib/php7.4-fpm/web41.sock:", host: "dev.xxx.com", referrer: "https://dev.xxx.com/"

**Comment by fatihtoprak** [comment]
php sürümünüzün min 7.4 olması gerekmekte bilginize.
