### ISSUE TITLE
fiyatların kaybolması sorunu

### ISSUE THREAD

**Issue by hunkardoner** [optimisthub/moka-woocommerce#18]
https://github.com/optimisthub/moka-woocommerce/commit/5ebe32da3262e716fb485c8e18c66a00b9f13ee2 commitinde gelen `add_filter( 'woocommerce_get_price_html', [$this, 'renderMinInstallmentMessage'] );` kısmıyla birlikte Flatsome temasında kataloglarda fiyatlar listelenmiyor. **core/library/Moka_Init.php** 30. satırı commitleyince fiyatlar geldi bilginize.

**Comment by fatihtoprak** [comment]
Güncelleme ile sorun çözülmüştür

**Comment by musabatas** [comment]
Woodmart temada aynı sorunla karşılaştım.
