### ISSUE TITLE
Taksit Tablosu Gösterim Hatası

### ISSUE THREAD

**Issue by ZgrK** [optimisthub/moka-woocommerce#19]
Merhabalar 

Amex kartlar için bir tablo geliyor fakat bunlar ayalarda -1 olarak seçili aşağıdaki görselde göründüğü gibi oluşuyor bunu tamamen gizleyebileceğimiz bir alan olsa güzel olur fiyat -1 fiyatlı olan taksitler gözükmese 

<img width="347" alt="image" src="https://user-images.githubusercontent.com/879674/207749125-5587a951-6ea8-4d93-b22c-1a1614adb119.png">

**Comment by cafemasasandalye** [comment]
Merhaba,

arkadaşa katılıyorum. düzenleme yapılırsa sevinirim.
