### ISSUE TITLE
Kredi Kartı Doldurma Yerinde Otomatik Doldurma da Taksit Sorunun

### ISSUE THREAD

**Issue by ZgrK** [optimisthub/moka-woocommerce#20]
Aşağıda ki kod keyup ile olduğu için sadece rakamlar girilirse taksit için ajax sorgusunu gönderiyor fakat bazi insanlar 1password gibi ya da browserin da kayediyorlar bu gibi insanlara taksit seçeneği çıkmıyor bunun için silip bir rakam yeniden yazmak gerekiyor 

Fakat bunun yerine keyup ile beraber change de eklenebilir.

https://github.com/optimisthub/moka-woocommerce/blob/d6f044603e327f75074cbfdba07f3c7bf4345d12/assets/moka.js#L9

**Comment by fatihtoprak** [comment]
güncellenen versiyonu dağıtmaya başladık almanızı tavsiye ederiz.
