### ISSUE TITLE
Listeleme sayfasında fiyatlar kayboluyor

### ISSUE THREAD

**Issue by musabatas** [optimisthub/moka-woocommerce#22]
Eklentiyi aktifleştirince listeleme/kategori sayfalarında fiyatlar görünmüyor. Tema olarak Woodmart kullanıyoruz. Daha önce bu sorunla karşılaşıldığını gördüm. Issue #18

**Comment by fatihtoprak** [comment]
Merhaba listeleme sayfalarında mı yoksa listeleme yapan bileşenlerde mi sorun yaşıyorsunuz ?

**Comment by musabatas** [comment]
Merhaba,

Sadece listeleme sayfasında değil. Listeleme bileşeni yani "product-grid-item" da sorun oluyor. bu alana herhangi bir müdahale'de bulunmadık. Ürün sayfalarına müdahale ettik. Ancak eklentileri devre dışı bırakıp denediğimizde de aynı sorunun devam ettiğini gördüm.

**Comment by ZgrK** [comment]
@musabatas Bizde Woodmart kullaniyoruz bir cok musterimizde mokapos bu eklentiyle beraber fakat eklentinin bir kac sürümü öncesinde böyle bir sorun vardı daha sonrasında @fatihtoprak bunu düzeltti son sürümde olduğuna emin misin ? 

3.5.7 sürümünde bunlar cözüldü

**Comment by fatihtoprak** [comment]
> Merhaba,
> 
> 
> 
> Sadece listeleme sayfasında değil. Listeleme bileşeni yani "product-grid-item" da sorun oluyor. bu alana herhangi bir müdahale'de bulunmadık. Ürün sayfalarına müdahale ettik. Ancak eklentileri devre dışı bırakıp denediğimizde de aynı sorunun devam ettiğini gördüm.

Merhaba dediğim gibi, ilgili üstte yazdığınız referans issue'de alakalı lokasyondaki Moka_Core.php de bir filtre var bu loop kısmında farklı davranmayı sağlıyor. Bahsi geçen plugin veya tema ile gelen widget evrensel değerler veya yaklaşımlar dışında çözüm üretiyorsa sizin kendinize özel o kısmı geliştirmeniz gerekli.

Dilerseniz o kısmı return $price olarak dönerek hariç tutabilirsiniz.
