### ISSUE TITLE
Taksitlerin görünmemesi hk.

### ISSUE THREAD

**Issue by cafemasasandalye** [optimisthub/moka-woocommerce#23]
Merhaba,

yönetim panelinde taksitli satış özelliği aktif olduğu halde sepette sadece tek çekim gözükmektedir. bunu konuyla ilgili bir düzenleme varmı acaba?

iyi çalışmalar dilerim. 

![image](https://user-images.githubusercontent.com/58148690/212653792-fd7048e6-f7c0-4128-9aac-823f84b54d67.png)

**Comment by cafemasasandalye** [comment]
@fatihtoprak @optimistlab

**Comment by fatihtoprak** [comment]
güncellenen versiyonu dağıtmaya başladık almanızı tavsiye ederiz.
