### ISSUE TITLE
Ödeme sonrası sepet sayfası sorunu

### ISSUE THREAD

**Issue by kadirturan0** [optimisthub/moka-woocommerce#24]
Ödeme onay sms'i girdikten sonra sonuç sayfası yerine tekrar sepet sayfasına yönlendiriliyor. sorunun kaynağını bulamadım.

**Comment by optimistlab** [comment]
Selamlar @kadirturan0 
Bunun pek çok nedeni olabilir. 
admin@optimishub.com üzerinden sorunun detayını açıklayan, hata çıktıları / ekran görüntülerini, kullanılan WP ve Woocommerce sürümünü ve website URL'nizi de içerir şekilde bizimle iletişim kurabilir misiniz?
Teşekkürler.

**Comment by trgino** [comment]
Woocommerce -> Ayarlar -> Gelişmiş sayfasında 
"Ödeme sayfası" ayarında bir sayfa seçildiğinden ve seçilen sayfada [woocommerce_checkout] yazılı olduğundan emin olunuz.
