### ISSUE TITLE
Ödeme sayfasında taksit seçenekleri

### ISSUE THREAD

**Issue by ibocan586** [optimisthub/moka-woocommerce#25]
Ödeme sayfasında Tek Çekim x 20,360.00 TRY gözüküyor ama diğer taksit seçenekleri gözükmüyor

**Comment by trgino** [comment]
Woocommerce -> Ayarlar -> Ödeme -> Moka by Isbank -> Yönet butonuyla ulaşacağınız ödeme yöntemi ayar sayfasından "Taksitli Alışveriş" seçeneğini aktifleştirebilirsiniz. 
Aktifleştirdiğiniz halde taksit seçenekleri gözükmüyor ise bunun bir kaç sebebi olabilir: 
- Yazdığınız kart için taksit seçeneği bulunmayabilir. 
- Moka üyeliğinizde taksit aktif olmayabilir. 
- Sunucunuz, Moka sunucularıyla iletişimde problemler yaşıyor olabilir.
