### ISSUE TITLE
Multi Currency

### ISSUE THREAD

**Issue by musabatas** [optimisthub/moka-woocommerce#26]
https://docs.villatheme.com/woocommerce-multi-currency/#page_section_menu_6680

Yukarıdaki para birimi eklentisini kullanılırken ödeme sayfasında seçili para birimi yerine woocommerce standard para birimi gösteriliyor.

https://github.com/optimisthub/moka-woocommerce/blob/67b7a6acbca5257e35c84dd4ee729b8e5f09638a/core/library/Optimisthub_Ajax.php#L13

https://github.com/optimisthub/moka-woocommerce/blob/67b7a6acbca5257e35c84dd4ee729b8e5f09638a/core/library/Moka_Init.php#L155

https://github.com/optimisthub/moka-woocommerce/blob/67b7a6acbca5257e35c84dd4ee729b8e5f09638a/core/library/Moka_Init.php#L156

**Comment by trgino** [comment]
öncelikle Moka nın TRY dışında diğer para birimleri için taksit yapmadığını belirtmek isterim. 
kullanılacak para miktarı değeri için; 
- cart aşamasındayken $wocommerce globalindeki cart total 
- order aşamasındayken order get_total
kullanılmaktadır.
yeni güncelleme ile birlikte;
para birimi sembolu için get_woocommerce_currency_symbol fonksiyonu kullanılmaktadır; gösterilen para birimi sembolunu değiştirmek için woocommerce_currency_symbol veya woocommerce_currency filtresini kullanabilirsiniz
