### ISSUE TITLE
Taksit seçenekleri çıkmıyor.

### ISSUE THREAD

**Issue by adburbs** [optimisthub/moka-woocommerce#27]
Merhaba,

Taksit seçenkleri maalesef kartların hiçbirinde çıkmıyor.

**Comment by trgino** [comment]
eklenti ayarları kısmında "üye iş yeri bilgilerini test et" butonu ile kısa bir test çalıştırabilirsiniz. akabinde moka pay e bin sorgulama izinlerinizin verilip verilmediği sorabilirsiniz.
