### ISSUE TITLE
Can't activate plugin

### ISSUE THREAD

**Issue by musabatas** [optimisthub/moka-woocommerce#3]
I got an error when i try to activate plugin.

`Cannot redeclare wp_install_maybe_enable_pretty_permalinks() (previously declared in ... /wp-admin/includes/upgrade.php:478)`

**Comment by fatihtoprak** [comment]
Have you ever try to install , our plugin without other plugins ? 

Seems like, another plugin install.

**Comment by musabatas** [comment]
I have deactivated all extensions and then activate Woocommerce and Moka extensions and then activate other plugins. It worked this way. I didn't catch which plugin causes this issue. I will try to get a log for you.

**Comment by fatihtoprak** [comment]
Sure please share your logs if you get.
