### ISSUE TITLE
Çoklu para birimi hatası

### ISSUE THREAD

**Issue by ZgrK** [optimisthub/moka-woocommerce#4]
Merhabalar 

Eğer eklentiyle beraber çoklu para birimi eklentilerinden birisi kullanılırsa ve  ana para birmi USD olarak ayarlanırsa taksitli bir kartla YTL olarak satın alma işlemi tamamlanırken çıkan taksitli kart seçeneği USD para birimi olarak gösteriyor.

Ayrıca para birimi USD ise ve taksitli bir kartla satın alma denenirse ki bankacılık kanunun göre böyle birşey olmaması lazım onuda taksitlendiriyor USD para biriminde Odeme yapmayı denemedım ama binvalidate yapıyor bu kısımda.

**Comment by ZgrK** [comment]
Bu sorun icin bir guncelleme gelecek mi yakinda @fatihtoprak planlama nedir bunun icin ?

**Comment by ZgrK** [comment]
Bu sorunun biraz inceledim kartı yazarken böyle bir method var taksitler için 

action: 
optimisthub_ajax
method: 
validate_bin


daha sonrasında html render daki currency hatalı geliyor 

https://github.com/optimisthub/moka-woocommerce/blob/d6f044603e327f75074cbfdba07f3c7bf4345d12/core/library/Optimisthub_Ajax.php#L237

                      
                        
                        
                        Zaten taksit varsa sadece Türk Lirasında olabiliyor tek çekimde artık sistem göstermiyorda buna bir genel yenilik düşünmek gerek bence

**Comment by fatihtoprak** [comment]
merhaba , debug için teşekkürler peki;

`get_option('woocommerce_currency');`

bu alan değil mi currency'i setlediğimiz kısım, burada uygulanması gereken nedir? 

Bildiğim kadarı ile bu kısımda, order a göre ilerlemek doğru olan genel currency'i setlemek mantıklı değil gibi duruyor.

Ya da currency değiştiren eklenti isimleri nelerdir? Ya da siz kendi projenizde bu durumu nasıl handle ediyorsunuz ? Farklı currency'leri ne şekilde servis ediyorsunuz ?

@ZgrK ne düşünürsünüz bu konuda ?

**Comment by ZgrK** [comment]
@fatihtoprak Simdi soyle bir durum var benim bildigim kadariyla regulasyona gore zaten Türkiye'de ki hiç bir banka Türk Lirası dışında taksit yapamıyor. 

Türk lirasının koruma kanunun gibi bir durum olması lazım mesela burada dolar bile göndersen taksit yapmak istersen Türk lirası ile yapıyor o taksiti genel sistemde o yüzden burada bir currency belirlemek doğrumu buna emin değilim. 

Onun dısında get option ile alırsan eğer default olarak seçilen para birimi geliyor bunu 

get_woocommerce_currency() ile almak gerekiyor.

**Comment by fatihtoprak** [comment]
güncelleme ile taksit kısmındaki sorun giderildi. 
teşekkürler @ZgrK

**Comment by ZgrK** [comment]
Malesef bu son guncellemede duzelmemis gozukuyor 
<img width="612" alt="image" src="https://user-images.githubusercontent.com/879674/221405786-4d5f8d96-3c3d-49b7-8ce2-293100c2d61c.png">
