### ISSUE TITLE
Taksit Seçeneklerinin ürünlerde gösterilmesi 

### ISSUE THREAD

**Issue by ZgrK** [optimisthub/moka-woocommerce#5]
Merhabalar 

Teknik olarak bir önerim olacak bir Türkiye de ki bir çok e-ticaret sitesinde olan bir özelliği eklentiye getirirseniz baya etkili olacağını düşünüyorum ornegin hepsiburada da oldugu gibi taksit eklenmesi woocommerce daki tablara bu sekme eklenebilir eklentinin ayarlarından bu özelliği kapatıp açma eklenebilir ayrıca hali hazırda arka tarafta yüzde girildiği için girilen yüzdelerle bu tablolar oluşturulabilir. 
![image](https://user-images.githubusercontent.com/879674/189175464-fbad15a6-2d1b-4cd4-ac67-827b02518754.png)

**Comment by fatihtoprak** [comment]
Merhaba @ZgrK bu güzel bir feature olacak. İlerleyen süreçte iş listemize dahil ediyoruz. Teşekkürler.

**Comment by fatihtoprak** [comment]
Güncelleme ile (3.5 versiyonu) artık bu nitelik sistem içerisine dahil edilmiştir.
