### ISSUE TITLE
Satın alma sayfası taksit UX hatası

### ISSUE THREAD

**Issue by ZgrK** [optimisthub/moka-woocommerce#6]
Satın alma adımına gelindiğinde hazırlanmış olan dropdown şeklinde yer alan taksitlendirme yapısı baya kötü oluyor kullanıcılar tarafından geri dönüş olarak hep farklı sorunlar yansıyor bunun yerine seçenekler tablo seklinde oluşsa eğer taksit yapılabilecek bir kart değilse direk tek çekim olarak kalsa bir dropdown gözükmese çok daha verimli olabilir eklenti için.

**Comment by fatihtoprak** [comment]
Merhaba geri bildirim için teşekkürler. Bu alan ile alakalı deneyiminiz çok değerli. Geliştirme lisemize dahil ediyorum.
