### ISSUE TITLE
Moka Pay ile tekrarlayan ödemeler servisinin entegrasyonu

### ISSUE THREAD

**Issue by fatihtoprak** [optimisthub/moka-woocommerce#7]
Moka Pay ile WooCommerce üzerinden abonelikli ödemeler / tekrarlayan ödemeler satışı yapılması.

**Comment by fatihtoprak** [comment]
- [x] Tekrarlayan ödemelerin servisleri implementasyonu.
- [x] WordPress Admin panel üzerinde tüm tekrarlı ödemelerin listelenmesi ve düzenlenebilir olması.
- [x] WooCommerce kullanıcı arayüzünde ödemelerin listelenmesi ve düzenlenebilir olması.
- [x] WooCommerce admin panel üzerinde siparişler içerisinde periyodik ödemelerin entegrasyonu.
- [ ] Wp Cron ile ödemelerin tekrarlanmasının sağlanması.
- [ ] Tekrarlı ödemelerin satışlarının loglanması.

**Comment by fatihtoprak** [comment]
Subscription period already formatted for logs.

![Image](https://user-images.githubusercontent.com/2514952/190821794-b9d16e90-8cbf-4316-8071-eb0b5434f581.png)

**Comment by fatihtoprak** [comment]
Wp Cron ile ödemelerin tekrarlanmasının sağlanması. Bu senaryo için yeni issue açıldı #9

**Comment by fatihtoprak** [comment]
Wp Cron ile ödemelerin tekrarlanmasının sağlanması. Bu senaryo için yeni issue açıldı #9

**Comment by MartinPaliesek** [comment]
Nnj
